version: 2
jobs:
  tests:
    docker:
      - image: cimg/node:12.22.11
    steps:
      - checkout
      - run: npm ci
      - run: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: npm whoami
      - run: npm test
      - run: npm run semantic-release || true

workflows:
  version: 2
  build:
    jobs:
      - tests
